services:
    pplpack_api:
        container_name: pplpack_api
        volumes:
            - ./data:/app/data
            - ./uploads:/app/uploads
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - nginx
        environment:
            - TZ=Europe/Moscow
        restart: always
        command: npm run start

networks:
    nginx:
        external: true
        name: nginx
